# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
    - master
    - dev
    - feature/*
  paths:
    include:
    - backend/*
    exclude:
    - frontend/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      python.version: '3.7.6'
    mac:
      imageName: 'macos-10.14'
      python.version: '3.7.6'
    windows:
      imageName: 'vs2017-win2016'
      python.version: '3.7.6'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    cd backend
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd backend
    pip install pytest coverage
    coverage run -m pytest --junitxml=$(System.DefaultWorkingDirectory)/reports/flask-basic-test.xml
    coverage report
    coverage html -d $(System.DefaultWorkingDirectory)/reports/htmlcov
    coverage xml -o $(System.DefaultWorkingDirectory)/reports/flask-basic-coverage.xml
  displayName: 'pytest with coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'reports/flask-basic-test.xml'
    testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version)'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/reports/flask-basic-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/reports/htmlcov'